#' plot_connectivity2d
#' @description
#' function to plot the connnectivity 2D projection according to the given community partition
#'
#' @param coordinate node seq generated by the connectivity analysis
#' @param community community in order of the nodes' labels. should be int vector
#' @return visualization of the 2d-connnectivity and the community partition
#' @export
#'
plot_connectivity2d=function(coordinate,community,col_given=NULL)
{
  N=nrow(coordinate);aa=coordinate[,1];bb=coordinate[,2]
  if(length(col_given)==0){col_list=rainbow(length(unique(community)))}
  else{col_list=col_given}
  plot(aa,bb,col="grey",xlab="coordinate 1",ylab="coordinate 2")
  for (i in 1:N)
  {
    points(aa[i],bb[i],col=col_list[community[i]],,pch=20)
  }

}
