#' plot_connectivity
#' @description
#' function to plot the connnectivity and the community partition
#'
#' @param node_seq node seq generated by the connectivity analysis
#' @param connectivity_seq connectivity seq smoothed according to alpha
#' @param community community in order of the nodes' labels
#' @return visualization of the connnectivity and the community partition
#' @export
#'
plot_connectivity=function (node_seq, connectivity_seq, community, y = 0.8, col_given = NULL)
{
  community = community[as.numeric(node_seq)]
  connect_record_smooth = connectivity_seq
  nodes_ = node_seq
  partition_ = community
  plot_data_fda = plot_data_function(temp_seq = node_seq, temp_connect_record = connect_record_smooth,
                                     temp_community_df = cbind(nodes_, partition_), col_given = col_given)
  plot(1:nrow(plot_data_fda), plot_data_fda$connect_record,lty=2,col="grey",
       ylim = c(0, y), xlab = "node",
       ylab = "dependency")
  lines(1:nrow(plot_data_fda), plot_data_fda$connect_record,lty=2,col="grey")
  points(1:nrow(plot_data_fda), plot_data_fda$connect_record,
         col = plot_data_fda$color,pch=20)
}
