#' wavelet_test_long_rg
#' @description
#' function to test community scale using wavelet analysis
#'
#' @param adj_mat adjacency matrix, N columns
#' @param tuning_in tuning_in,default 0
#' @param tuning_out tuning_out default 1
#' @param length_seq length of each seq
#' @param memory dependence memory, default 60
#' @param sample_memory sample_memory, default N
#' @param m node seq generated by the connectivity analysis
#' @return power_all: power of different frequency at each node;node_all:node sequences in m samples; seq_all:dependence sequences in m samples; local_sum_mean:mean power at each node;local_sum_sd: sd of the power at each node;period: period of the wavelet basis
#' @export
#'
#'
wavelet_test_long_rg=function(adj_mat,tuning_in=0,tuning_out=1,length_seq,memory=60,sample_memory,m=100,alpha=1)
{
  N=ncol(adj_mat)
  mean_mat=NULL
  sd_mat=NULL
  n_seq=NULL
  #抽取的时候不抽memeory有关的
  power_all=NULL
  period_all=NULL
  node_all=NULL
  seq_all=NULL
  for(j in 1:m)
  {
    adj_mat_rg=random_adj_mat(adj_mat)
    temp_connectivity=connectivity_seq(adj_mat_rg,tuning_in = tuning_in,tuning_out = tuning_out,memory = memory,sample_memory =N,length_seq =N,seeds = j,alpha = alpha)
    temp_node=temp_connectivity$node_seq[(memory+1):(length_seq-memory)]
    temp_seq=temp_connectivity$connect_record_smooth[(memory+1):(length_seq-memory)]
    x=temp_seq
    min_scale=1
    my.data = data.frame(x=x)
    my.wt = analyze.wavelet(my.data, "x",
                            loess.span=0,
                            dt=1, dj=1/20,
                            lowerPeriod=2,
                            upperPeriod = length(temp_seq),
                            make.pval=F, n.sim=10,verbose = F)
    #power列数是节点数--一定是cbind
    period_all=my.wt$Period
    power_all=cbind( power_all,my.wt$Ampl)
    node_all=c(node_all,temp_node)
    seq_all=c(seq_all,temp_seq)
  }
  #输出结果
  ava_node=sort(unique(as.numeric(node_all)))
  for(i in ava_node)
  {
    temp_power=as.matrix(power_all[,node_all%in%i],ncol=length(which(node_all%in%i)))
    temp_mean=apply(temp_power,1,mean)
    temp_n=ncol(temp_power)
    temp_sd=apply(temp_power,1,sd)
    mean_mat=cbind(mean_mat,temp_mean)
    sd_mat=cbind(sd_mat,temp_sd)
    n_seq=c(n_seq,temp_n)
  }

  rownames(sd_mat)=period_all; rownames(mean_mat)=period_all;
  colnames(sd_mat)=ava_node;colnames(mean_mat)=ava_node
  return(list(power_all=power_all,node_all=node_all,seq_all=seq_all,local_sum_mean=mean_mat,local_sum_sd=sd_mat,period=period_all,n_seq=n_seq))

}

