#' wavelet_test_function
#' @description
#' function to test community scale using wavelet analysis
#'
#' @param adj_mat adjacency matrix, N columns
#' @param tuning_in tuning_in,default 0
#' @param tuning_out tuning_out default 1
#' @param memory dependence memory, default 60
#' @param m node seq generated by the connectivity analysis
#' @param alpha smooth parameter for dependency value sequence
#' @return wavelet_test_long result for G and random G，matrix recording p-value and test statistics
#' @export
#'
#'
wavelet_test_function=function(adj_mat,memory=60,m=100,tuning_in=0,tuning_out=1,alpha=0.4)
{
  N=ncol(adj_mat)
  wavelet_1=wavelet_test_long(adj_mat,memory = memory,m=m,sample_memory = N,length_seq = N,alpha = alpha)
  wavelet_0=wavelet_test_long_rg(adj_mat,memory = memory,m=m,sample_memory = N,length_seq = N,alpha = alpha)
  test1=wavelet_1;test10=wavelet_0;
  mean_stat=(test1$local_sum_mean-apply(test1$local_sum_mean,1,mean))-(test10$local_sum_mean-apply(test10$local_sum_mean,1,mean))
  var_stat=test1$local_sum_sd^2/test1$n_seq+test10$local_sum_sd^2/test10$n_seq
  var_stat2=(test1$local_sum_sd^2+apply(test1$local_sum_sd^2,1,sum)/(ncol(test1$local_sum_sd)^2))/test1$n_seq+
    (test10$local_sum_sd^2+apply(test10$local_sum_sd^2,1,sum)/(ncol(test10$local_sum_sd)^2))/test10$n_seq
  test_stat=mean_stat/sqrt(var_stat)
  test_res1=pnorm(test_stat)
  p_mat=test_res1
  rownames(p_mat)=test1$period;rownames(test_stat)=test1$period
  return(list(wavelet_1=wavelet_1,wavelet_0=wavelet_0,p_mat=p_mat,test_stat=test_stat))
}

