#' plot_connectivity
#' @description
#' function to plot the connnectivity and the community partition
#'
#' @param node_seq node seq generated by the connectivity analysis
#' @param connectivity_seq connectivity seq smoothed according to alpha
#' @param community community in order of the nodes' labels
#' @return visualization of the connnectivity and the community partition
#' @export
#'
plot_connectivity=function(node_seq,connectivity_seq,community)
{
community=community[as.numeric(node_seq)]
connect_record_smooth=connectivity_seq
nodes_=node_seq
partition_=community

plot_data_fda=plot_data_function(node_seq,connect_record_smooth,cbind(nodes_,partition_))
plot(nodes_,connect_record_smooth,xlim=c(1,length(nodes_)),ylim=c(0,1),pch=20,col="white",xlab="node",ylab="connectivity")
points(1:nrow(plot_data_fda),plot_data_fda$connect_record,col=plot_data_fda$color)

}
