#' plot_connectivity2d
#' @description
#' function to plot the connnectivity 2D projection according to the given community partition
#'
#' @param coordinate node seq generated by the connectivity analysis
#' @param community community in order of the nodes' labels. should be int vector
#' @return visualization of the 2d-connnectivity and the community partition
#' @export
#'
plot_connectivity2d=function(coordinate,community)
{
  N=nrow(coordinate);aa=coordinate[,1];bb=coordinate[,2]
  col_list=rainbow(length(unique(community)))
  plot(aa,bb,col="white")
  for (i in 1:N)
  {
    points(aa[i],bb[i],col=col_list[community[i]])
  }

}
